"""
Description: Calculates physical coverage of Illumina short-reads in 10kb window
Author: Riccha Sethi
"""

import argparse
import math
import pandas as pd
pd.options.mode.chained_assignment=None

def calc_cov(File):
    chromosomes=File.chrom.unique()
    CHROM=[i for i in chromosomes if i.startswith("chr")]
    File['Multipled']=File['depth']* File['bases']
    SUM=0
    AllSize=0
    for chromo in CHROM:
        df=File[(File['chrom']==chromo) & (File['depth']<10000)]
        #SUM= df['Multipled'].sum(axis=0, skipna=True)
        SUM=SUM + df['Multipled'].sum(axis=0, skipna=True)
        AllSize=AllSize + df.iloc[0]['size']
    print SUM/AllSize
#        COV= SUM/df.iloc[0]['size']
#        print "chromo,SUM,size,COV",chromo,SUM,df.iloc[0]['size'],COV


if __name__=='__main__':
    parser=argparse.ArgumentParser(description="Python script to calculate physical coverage for short-reads from bedtools genomecov -pc generated files")
    parser.add_argument('-bed','--bedfile',help="enter bed file generated by genomecov -pc command")
    parser.add_argument('-out','--output', help="output tab-delimites file with pileup values")
    args=parser.parse_args()
    BED=pd.read_csv(args.bedfile, sep='\t', names=["chrom","depth","bases","size", "fraction_bases"])
    calc_cov(BED)
